---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-nas-sonar
mountOptions:
  - nolock,tcp,noresvport
  - vers=3
parameters:
  server: "0541648848-ora18.cn-hangzhou.nas.aliyuncs.com:/sonar/"
  driver: flexvolume
provisioner: alicloud/nas
reclaimPolicy: Retain