---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mip-gateway
  namespace: mip-system
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mip-gateway
      project: mip
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mip-gateway
        project: mip
    spec:
      containers:
        - env:
            - name: APP_OPTS
              value: '--spring.profiles.active=uat'
          image: 'registry.haid.com.cn/mip/mip-gateway:#IMAGE_TAG#'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 30102
            timeoutSeconds: 5
          name: gateway
          ports:
            - containerPort: 30102
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 30102
            timeoutSeconds: 10
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 125Mi
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: mip-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: mip-gateway-svc
  namespace: mip-system
spec:
  ports:
    - name: gateway
      port: 30102
      targetPort: 30102
  selector:
    project: mip
    app: mip-gateway

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mip-gateway-ingress
  namespace: mip-system
spec:
  rules:
    - host: mipqa.haid.com.cn
      http:
        paths:
        - path: /v999
          backend:
            serviceName: mip-gateway-svc
            servicePort: 30102
  tls:
    - hosts:
        - mipqa.haid.com.cn
      secretName: tls-haid.com.cn