---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    pvname: prometheus
  name: prometheus-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  flexVolume:
    driver: alicloud/nas
    options:
      modeType: non-recursive
      path: /mnt/prometheus
      server: 0541648848-ora18.cn-hangzhou.nas.aliyuncs.com
      vers: '3'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      alicloud-pvname: prometheus-pv
  storageClassName: nas
  volumeMode: Filesystem
  volumeName: prometheus-pv