apiVersion: v1
kind: Service
metadata:
  name: mip-cfca-recognize-server-svc
  namespace: mip-system
spec:
  clusterIP: 192.168.31.155
  ports:
    - name: svc-15001
      nodePort: 32576
      port: 15001
      protocol: TCP
      targetPort: 15001
  selector:
    module: cfca-recognize-server
    tier: backend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 10.200.36.214