apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
  creationTimestamp: '2020-04-15T08:46:00Z'
  name: mip-cfca-deepocr-svc
  namespace: mip-system
  resourceVersion: '840069983'
  selfLink: /api/v1/namespaces/mip-system/services/mip-cfca-deepocr-svc
  uid: 882b8494-7ef5-11ea-aba3-9698111c9a36
spec:
  clusterIP: 192.168.30.249
  ports:
    - name: svc-9000
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    module: cfca
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
