FROM ninech/jnlp-slave-with-docker

COPY tool /usr/local
USER root

RUN chmod -R 755 /usr/local/apache-maven-3.5.4/   && \
    chmod -R 755 /usr/local/node-11.12.0/ && \
    chmod -R 755 /usr/local/kubectl-v1.16.1/ && \
    ln -s /usr/local/apache-maven-3.5.4/bin/mvn  /usr/local/bin/mvn && \
    ln -s /usr/local/node-11.12.0/bin/npm  /usr/local/bin/npm && \
    ln -s /usr/local/kubectl-v1.16.1/kubectl /usr/local/bin/kubectl
