FROM openjdk:8-jre-alpine

# 环境变量
ENV WORK_PATH /home/project/app
ENV APP_NAME web/target/*.jar
ENV JAVA_OPTS -Xmx256m -Xss256k
ENV JAVA_VAR uat
ENV APP_OPTS=""

#COPY
COPY $APP_NAME $WORK_PATH/app.jar

# WORKDIR
WORKDIR $WORK_PATH

#GMT+8
RUN echo "Asia/Shanghai" > /etc/timezone


ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS  -jar app.jar  $APP_OPTS" ]