apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{"pv.kubernetes.io/bound-by-controller":"yes"},"finalizers":["kubernetes.io/pv-protection"],"labels":{"alicloud-pvname":"mip-log-pv"},"name":"mip-log-pv"},"spec":{"accessModes":["ReadWriteMany"],"capacity":{"storage":"30Gi"},"flexVolume":{"driver":"alicloud/nas","options":{"modeType":"non-recursive","path":"/project/mip/log","server":"05c2148af4-ulh72.cn-hangzhou.nas.aliyuncs.com","vers":"3"}},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"nas","volumeMode":"Filesystem"}}
    pv.kubernetes.io/bound-by-controller: 'yes'
  creationTimestamp: '2020-04-15T09:10:21Z'
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    alicloud-pvname: mip-log-pv
  name: mip-log-pv
  resourceVersion: '834370998'
  selfLink: /api/v1/persistentvolumes/mip-log-pv
  uid: ef02c2d0-7ef8-11ea-aba3-9698111c9a36
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mip-log-pvc
    namespace: mip-system
    resourceVersion: '834362917'
    uid: b2732d15-7ef8-11ea-aba3-9698111c9a36
  flexVolume:
    driver: alicloud/nas
    options:
      modeType: non-recursive
      path: /project/mip/log
      server: 05c2148af4-ulh72.cn-hangzhou.nas.aliyuncs.com
      vers: '3'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  volumeMode: Filesystem
status:
  phase: Bound
