apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-slave-pvc
  namespace: common-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      alicloud-pvname: jenkins-slave-pv
  storageClassName: nas
  volumeMode: Filesystem
  volumeName: jenkins-slave-pv