apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    alicloud-pvname: jenkins-pv
  name: jenkins-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 30Gi
  flexVolume:
    driver: alicloud/nas
    options:
      modeType: non-recursive
      path: /project/mip/jenkins
      server: 05c2148af4-ulh72.cn-hangzhou.nas.aliyuncs.com
      vers: '3'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  volumeMode: Filesystem